/* tslint:disable */
/* eslint-disable */
/**
 * Orbit Container Agent API
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppInstance,
  AppsAppIdLaunchPostRequest,
  ContainersContainerIdAppsPostRequest,
  Task,
} from '../models/index';
import {
    AppInstanceFromJSON,
    AppInstanceToJSON,
    AppsAppIdLaunchPostRequestFromJSON,
    AppsAppIdLaunchPostRequestToJSON,
    ContainersContainerIdAppsPostRequestFromJSON,
    ContainersContainerIdAppsPostRequestToJSON,
    TaskFromJSON,
    TaskToJSON,
} from '../models/index';

export interface AppsAppIdLaunchPostOperationRequest {
    appId: string;
    appsAppIdLaunchPostRequest?: AppsAppIdLaunchPostRequest;
}

export interface ContainersContainerIdAppsGetRequest {
    containerId: string;
}

export interface ContainersContainerIdAppsPostOperationRequest {
    containerId: string;
    containersContainerIdAppsPostRequest: ContainersContainerIdAppsPostRequest;
}

/**
 * 
 */
export class AppsApi extends runtime.BaseAPI {

    /**
     * Ejecutar una app
     */
    async appsAppIdLaunchPostRaw(requestParameters: AppsAppIdLaunchPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Task>> {
        if (requestParameters['appId'] == null) {
            throw new runtime.RequiredError(
                'appId',
                'Required parameter "appId" was null or undefined when calling appsAppIdLaunchPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/apps/{appId}/launch`;
        urlPath = urlPath.replace(`{${"appId"}}`, encodeURIComponent(String(requestParameters['appId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AppsAppIdLaunchPostRequestToJSON(requestParameters['appsAppIdLaunchPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskFromJSON(jsonValue));
    }

    /**
     * Ejecutar una app
     */
    async appsAppIdLaunchPost(requestParameters: AppsAppIdLaunchPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Task> {
        const response = await this.appsAppIdLaunchPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Listar apps dentro de un contenedor
     */
    async containersContainerIdAppsGetRaw(requestParameters: ContainersContainerIdAppsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AppInstance>>> {
        if (requestParameters['containerId'] == null) {
            throw new runtime.RequiredError(
                'containerId',
                'Required parameter "containerId" was null or undefined when calling containersContainerIdAppsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/containers/{containerId}/apps`;
        urlPath = urlPath.replace(`{${"containerId"}}`, encodeURIComponent(String(requestParameters['containerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AppInstanceFromJSON));
    }

    /**
     * Listar apps dentro de un contenedor
     */
    async containersContainerIdAppsGet(requestParameters: ContainersContainerIdAppsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AppInstance>> {
        const response = await this.containersContainerIdAppsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Instalar app dentro de contenedor
     */
    async containersContainerIdAppsPostRaw(requestParameters: ContainersContainerIdAppsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Task>> {
        if (requestParameters['containerId'] == null) {
            throw new runtime.RequiredError(
                'containerId',
                'Required parameter "containerId" was null or undefined when calling containersContainerIdAppsPost().'
            );
        }

        if (requestParameters['containersContainerIdAppsPostRequest'] == null) {
            throw new runtime.RequiredError(
                'containersContainerIdAppsPostRequest',
                'Required parameter "containersContainerIdAppsPostRequest" was null or undefined when calling containersContainerIdAppsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/containers/{containerId}/apps`;
        urlPath = urlPath.replace(`{${"containerId"}}`, encodeURIComponent(String(requestParameters['containerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ContainersContainerIdAppsPostRequestToJSON(requestParameters['containersContainerIdAppsPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskFromJSON(jsonValue));
    }

    /**
     * Instalar app dentro de contenedor
     */
    async containersContainerIdAppsPost(requestParameters: ContainersContainerIdAppsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Task> {
        const response = await this.containersContainerIdAppsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
