/* tslint:disable */
/* eslint-disable */
/**
 * Orbit Container Agent API
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Container,
  ContainersPostRequest,
  Task,
} from '../models/index';
import {
    ContainerFromJSON,
    ContainerToJSON,
    ContainersPostRequestFromJSON,
    ContainersPostRequestToJSON,
    TaskFromJSON,
    TaskToJSON,
} from '../models/index';

export interface ContainersContainerIdDeleteRequest {
    containerId: string;
}

export interface ContainersContainerIdGetRequest {
    containerId: string;
}

export interface ContainersGetRequest {
    status?: string;
}

export interface ContainersPostOperationRequest {
    containersPostRequest: ContainersPostRequest;
}

/**
 * 
 */
export class ContainersApi extends runtime.BaseAPI {

    /**
     * Eliminar contenedor
     */
    async containersContainerIdDeleteRaw(requestParameters: ContainersContainerIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Task>> {
        if (requestParameters['containerId'] == null) {
            throw new runtime.RequiredError(
                'containerId',
                'Required parameter "containerId" was null or undefined when calling containersContainerIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/containers/{containerId}`;
        urlPath = urlPath.replace(`{${"containerId"}}`, encodeURIComponent(String(requestParameters['containerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskFromJSON(jsonValue));
    }

    /**
     * Eliminar contenedor
     */
    async containersContainerIdDelete(requestParameters: ContainersContainerIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Task> {
        const response = await this.containersContainerIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Obtener contenedor
     */
    async containersContainerIdGetRaw(requestParameters: ContainersContainerIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Container>> {
        if (requestParameters['containerId'] == null) {
            throw new runtime.RequiredError(
                'containerId',
                'Required parameter "containerId" was null or undefined when calling containersContainerIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/containers/{containerId}`;
        urlPath = urlPath.replace(`{${"containerId"}}`, encodeURIComponent(String(requestParameters['containerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContainerFromJSON(jsonValue));
    }

    /**
     * Obtener contenedor
     */
    async containersContainerIdGet(requestParameters: ContainersContainerIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Container> {
        const response = await this.containersContainerIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Listar contenedores
     */
    async containersGetRaw(requestParameters: ContainersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Container>>> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/containers`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ContainerFromJSON));
    }

    /**
     * Listar contenedores
     */
    async containersGet(requestParameters: ContainersGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Container>> {
        const response = await this.containersGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Crear contenedor
     */
    async containersPostRaw(requestParameters: ContainersPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Task>> {
        if (requestParameters['containersPostRequest'] == null) {
            throw new runtime.RequiredError(
                'containersPostRequest',
                'Required parameter "containersPostRequest" was null or undefined when calling containersPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/containers`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ContainersPostRequestToJSON(requestParameters['containersPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskFromJSON(jsonValue));
    }

    /**
     * Crear contenedor
     */
    async containersPost(requestParameters: ContainersPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Task> {
        const response = await this.containersPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
