/* tslint:disable */
/* eslint-disable */
/**
 * Orbit Container Agent API
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiToken,
  ApiTokenCreated,
  SecurityStatus,
  SecurityTokensPostRequest,
} from '../models/index';
import {
    ApiTokenFromJSON,
    ApiTokenToJSON,
    ApiTokenCreatedFromJSON,
    ApiTokenCreatedToJSON,
    SecurityStatusFromJSON,
    SecurityStatusToJSON,
    SecurityTokensPostRequestFromJSON,
    SecurityTokensPostRequestToJSON,
} from '../models/index';

export interface SecurityTokensPostOperationRequest {
    securityTokensPostRequest: SecurityTokensPostRequest;
}

export interface SecurityTokensTokenIdDeleteRequest {
    tokenId: string;
}

/**
 * 
 */
export class SecurityApi extends runtime.BaseAPI {

    /**
     * Listar tokens de servicio emitidos
     */
    async securityTokensGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiToken>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/security/tokens`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiTokenFromJSON));
    }

    /**
     * Listar tokens de servicio emitidos
     */
    async securityTokensGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiToken>> {
        const response = await this.securityTokensGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Emitir un token de servicio
     */
    async securityTokensPostRaw(requestParameters: SecurityTokensPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiTokenCreated>> {
        if (requestParameters['securityTokensPostRequest'] == null) {
            throw new runtime.RequiredError(
                'securityTokensPostRequest',
                'Required parameter "securityTokensPostRequest" was null or undefined when calling securityTokensPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/security/tokens`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SecurityTokensPostRequestToJSON(requestParameters['securityTokensPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiTokenCreatedFromJSON(jsonValue));
    }

    /**
     * Emitir un token de servicio
     */
    async securityTokensPost(requestParameters: SecurityTokensPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiTokenCreated> {
        const response = await this.securityTokensPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Revocar token
     */
    async securityTokensTokenIdDeleteRaw(requestParameters: SecurityTokensTokenIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['tokenId'] == null) {
            throw new runtime.RequiredError(
                'tokenId',
                'Required parameter "tokenId" was null or undefined when calling securityTokensTokenIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/security/tokens/{tokenId}`;
        urlPath = urlPath.replace(`{${"tokenId"}}`, encodeURIComponent(String(requestParameters['tokenId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Revocar token
     */
    async securityTokensTokenIdDelete(requestParameters: SecurityTokensTokenIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.securityTokensTokenIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Recargar configuración y tokens estáticos desde variables de entorno
     */
    async systemSecurityReloadPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SecurityStatus>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/system/security/reload`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SecurityStatusFromJSON(jsonValue));
    }

    /**
     * Recargar configuración y tokens estáticos desde variables de entorno
     */
    async systemSecurityReloadPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SecurityStatus> {
        const response = await this.systemSecurityReloadPostRaw(initOverrides);
        return await response.value();
    }

}
