/* tslint:disable */
/* eslint-disable */
/**
 * Orbit Container Agent API
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ContainersContainerIdSnapshotsPostRequest,
  Snapshot,
  Task,
} from '../models/index';
import {
    ContainersContainerIdSnapshotsPostRequestFromJSON,
    ContainersContainerIdSnapshotsPostRequestToJSON,
    SnapshotFromJSON,
    SnapshotToJSON,
    TaskFromJSON,
    TaskToJSON,
} from '../models/index';

export interface ContainersContainerIdSnapshotsGetRequest {
    containerId: string;
}

export interface ContainersContainerIdSnapshotsPostOperationRequest {
    containerId: string;
    containersContainerIdSnapshotsPostRequest?: ContainersContainerIdSnapshotsPostRequest;
}

export interface SnapshotsSnapshotIdRestorePostRequest {
    snapshotId: string;
}

/**
 * 
 */
export class SnapshotsApi extends runtime.BaseAPI {

    /**
     * Listar snapshots
     */
    async containersContainerIdSnapshotsGetRaw(requestParameters: ContainersContainerIdSnapshotsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Snapshot>>> {
        if (requestParameters['containerId'] == null) {
            throw new runtime.RequiredError(
                'containerId',
                'Required parameter "containerId" was null or undefined when calling containersContainerIdSnapshotsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/containers/{containerId}/snapshots`;
        urlPath = urlPath.replace(`{${"containerId"}}`, encodeURIComponent(String(requestParameters['containerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SnapshotFromJSON));
    }

    /**
     * Listar snapshots
     */
    async containersContainerIdSnapshotsGet(requestParameters: ContainersContainerIdSnapshotsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Snapshot>> {
        const response = await this.containersContainerIdSnapshotsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Crear snapshot
     */
    async containersContainerIdSnapshotsPostRaw(requestParameters: ContainersContainerIdSnapshotsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Task>> {
        if (requestParameters['containerId'] == null) {
            throw new runtime.RequiredError(
                'containerId',
                'Required parameter "containerId" was null or undefined when calling containersContainerIdSnapshotsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/containers/{containerId}/snapshots`;
        urlPath = urlPath.replace(`{${"containerId"}}`, encodeURIComponent(String(requestParameters['containerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ContainersContainerIdSnapshotsPostRequestToJSON(requestParameters['containersContainerIdSnapshotsPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskFromJSON(jsonValue));
    }

    /**
     * Crear snapshot
     */
    async containersContainerIdSnapshotsPost(requestParameters: ContainersContainerIdSnapshotsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Task> {
        const response = await this.containersContainerIdSnapshotsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Restaurar snapshot
     */
    async snapshotsSnapshotIdRestorePostRaw(requestParameters: SnapshotsSnapshotIdRestorePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Task>> {
        if (requestParameters['snapshotId'] == null) {
            throw new runtime.RequiredError(
                'snapshotId',
                'Required parameter "snapshotId" was null or undefined when calling snapshotsSnapshotIdRestorePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/snapshots/{snapshotId}/restore`;
        urlPath = urlPath.replace(`{${"snapshotId"}}`, encodeURIComponent(String(requestParameters['snapshotId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskFromJSON(jsonValue));
    }

    /**
     * Restaurar snapshot
     */
    async snapshotsSnapshotIdRestorePost(requestParameters: SnapshotsSnapshotIdRestorePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Task> {
        const response = await this.snapshotsSnapshotIdRestorePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
