/* tslint:disable */
/* eslint-disable */
/**
 * Orbit Container Agent API
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiToken
 */
export interface ApiToken {
    /**
     * 
     * @type {string}
     * @memberof ApiToken
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ApiToken
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ApiToken
     */
    prefix: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiToken
     */
    scopes?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof ApiToken
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ApiToken
     */
    expiresAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ApiToken
     */
    lastUsedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ApiToken
     */
    revokedAt?: Date;
}

/**
 * Check if a given object implements the ApiToken interface.
 */
export function instanceOfApiToken(value: object): value is ApiToken {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('prefix' in value) || value['prefix'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ApiTokenFromJSON(json: any): ApiToken {
    return ApiTokenFromJSONTyped(json, false);
}

export function ApiTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiToken {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'prefix': json['prefix'],
        'scopes': json['scopes'] == null ? undefined : json['scopes'],
        'createdAt': (new Date(json['created_at'])),
        'expiresAt': json['expires_at'] == null ? undefined : (new Date(json['expires_at'])),
        'lastUsedAt': json['last_used_at'] == null ? undefined : (new Date(json['last_used_at'])),
        'revokedAt': json['revoked_at'] == null ? undefined : (new Date(json['revoked_at'])),
    };
}

export function ApiTokenToJSON(json: any): ApiToken {
    return ApiTokenToJSONTyped(json, false);
}

export function ApiTokenToJSONTyped(value?: ApiToken | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'prefix': value['prefix'],
        'scopes': value['scopes'],
        'created_at': value['createdAt'].toISOString(),
        'expires_at': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'last_used_at': value['lastUsedAt'] == null ? value['lastUsedAt'] : value['lastUsedAt'].toISOString(),
        'revoked_at': value['revokedAt'] == null ? value['revokedAt'] : value['revokedAt'].toISOString(),
    };
}

