/* tslint:disable */
/* eslint-disable */
/**
 * Orbit Container Agent API
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiToken } from './ApiToken';
import {
    ApiTokenFromJSON,
    ApiTokenFromJSONTyped,
    ApiTokenToJSON,
    ApiTokenToJSONTyped,
} from './ApiToken';

/**
 * 
 * @export
 * @interface ApiTokenCreated
 */
export interface ApiTokenCreated {
    /**
     * Token completo devuelto solo una vez
     * @type {string}
     * @memberof ApiTokenCreated
     */
    token: string;
    /**
     * 
     * @type {ApiToken}
     * @memberof ApiTokenCreated
     */
    info: ApiToken;
}

/**
 * Check if a given object implements the ApiTokenCreated interface.
 */
export function instanceOfApiTokenCreated(value: object): value is ApiTokenCreated {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('info' in value) || value['info'] === undefined) return false;
    return true;
}

export function ApiTokenCreatedFromJSON(json: any): ApiTokenCreated {
    return ApiTokenCreatedFromJSONTyped(json, false);
}

export function ApiTokenCreatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTokenCreated {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'info': ApiTokenFromJSON(json['info']),
    };
}

export function ApiTokenCreatedToJSON(json: any): ApiTokenCreated {
    return ApiTokenCreatedToJSONTyped(json, false);
}

export function ApiTokenCreatedToJSONTyped(value?: ApiTokenCreated | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'info': ApiTokenToJSON(value['info']),
    };
}

