/* tslint:disable */
/* eslint-disable */
/**
 * Orbit Container Agent API
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppInstanceEntryPointsInner } from './AppInstanceEntryPointsInner';
import {
    AppInstanceEntryPointsInnerFromJSON,
    AppInstanceEntryPointsInnerFromJSONTyped,
    AppInstanceEntryPointsInnerToJSON,
    AppInstanceEntryPointsInnerToJSONTyped,
} from './AppInstanceEntryPointsInner';

/**
 * 
 * @export
 * @interface AppInstance
 */
export interface AppInstance {
    /**
     * 
     * @type {string}
     * @memberof AppInstance
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AppInstance
     */
    containerId: string;
    /**
     * 
     * @type {string}
     * @memberof AppInstance
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AppInstance
     */
    version?: string;
    /**
     * 
     * @type {string}
     * @memberof AppInstance
     */
    status: AppInstanceStatusEnum;
    /**
     * 
     * @type {Array<AppInstanceEntryPointsInner>}
     * @memberof AppInstance
     */
    entryPoints?: Array<AppInstanceEntryPointsInner>;
    /**
     * 
     * @type {Date}
     * @memberof AppInstance
     */
    createdAt?: Date;
}


/**
 * @export
 */
export const AppInstanceStatusEnum = {
    Installing: 'installing',
    Ready: 'ready',
    Failed: 'failed',
    Disabled: 'disabled'
} as const;
export type AppInstanceStatusEnum = typeof AppInstanceStatusEnum[keyof typeof AppInstanceStatusEnum];


/**
 * Check if a given object implements the AppInstance interface.
 */
export function instanceOfAppInstance(value: object): value is AppInstance {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('containerId' in value) || value['containerId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function AppInstanceFromJSON(json: any): AppInstance {
    return AppInstanceFromJSONTyped(json, false);
}

export function AppInstanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppInstance {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'containerId': json['container_id'],
        'name': json['name'],
        'version': json['version'] == null ? undefined : json['version'],
        'status': json['status'],
        'entryPoints': json['entry_points'] == null ? undefined : ((json['entry_points'] as Array<any>).map(AppInstanceEntryPointsInnerFromJSON)),
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function AppInstanceToJSON(json: any): AppInstance {
    return AppInstanceToJSONTyped(json, false);
}

export function AppInstanceToJSONTyped(value?: AppInstance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'container_id': value['containerId'],
        'name': value['name'],
        'version': value['version'],
        'status': value['status'],
        'entry_points': value['entryPoints'] == null ? undefined : ((value['entryPoints'] as Array<any>).map(AppInstanceEntryPointsInnerToJSON)),
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

