/* tslint:disable */
/* eslint-disable */
/**
 * Orbit Container Agent API
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppInstanceEntryPointsInner
 */
export interface AppInstanceEntryPointsInner {
    /**
     * 
     * @type {string}
     * @memberof AppInstanceEntryPointsInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AppInstanceEntryPointsInner
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof AppInstanceEntryPointsInner
     */
    command?: string;
    /**
     * 
     * @type {string}
     * @memberof AppInstanceEntryPointsInner
     */
    icon?: string;
}

/**
 * Check if a given object implements the AppInstanceEntryPointsInner interface.
 */
export function instanceOfAppInstanceEntryPointsInner(value: object): value is AppInstanceEntryPointsInner {
    return true;
}

export function AppInstanceEntryPointsInnerFromJSON(json: any): AppInstanceEntryPointsInner {
    return AppInstanceEntryPointsInnerFromJSONTyped(json, false);
}

export function AppInstanceEntryPointsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppInstanceEntryPointsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'label': json['label'] == null ? undefined : json['label'],
        'command': json['command'] == null ? undefined : json['command'],
        'icon': json['icon'] == null ? undefined : json['icon'],
    };
}

export function AppInstanceEntryPointsInnerToJSON(json: any): AppInstanceEntryPointsInner {
    return AppInstanceEntryPointsInnerToJSONTyped(json, false);
}

export function AppInstanceEntryPointsInnerToJSONTyped(value?: AppInstanceEntryPointsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'label': value['label'],
        'command': value['command'],
        'icon': value['icon'],
    };
}

