/* tslint:disable */
/* eslint-disable */
/**
 * Orbit Container Agent API
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppsAppIdLaunchPostRequest
 */
export interface AppsAppIdLaunchPostRequest {
    /**
     * 
     * @type {string}
     * @memberof AppsAppIdLaunchPostRequest
     */
    entryPointId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AppsAppIdLaunchPostRequest
     */
    args?: Array<string>;
}

/**
 * Check if a given object implements the AppsAppIdLaunchPostRequest interface.
 */
export function instanceOfAppsAppIdLaunchPostRequest(value: object): value is AppsAppIdLaunchPostRequest {
    return true;
}

export function AppsAppIdLaunchPostRequestFromJSON(json: any): AppsAppIdLaunchPostRequest {
    return AppsAppIdLaunchPostRequestFromJSONTyped(json, false);
}

export function AppsAppIdLaunchPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppsAppIdLaunchPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'entryPointId': json['entry_point_id'] == null ? undefined : json['entry_point_id'],
        'args': json['args'] == null ? undefined : json['args'],
    };
}

export function AppsAppIdLaunchPostRequestToJSON(json: any): AppsAppIdLaunchPostRequest {
    return AppsAppIdLaunchPostRequestToJSONTyped(json, false);
}

export function AppsAppIdLaunchPostRequestToJSONTyped(value?: AppsAppIdLaunchPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entry_point_id': value['entryPointId'],
        'args': value['args'],
    };
}

