/* tslint:disable */
/* eslint-disable */
/**
 * Orbit Container Agent API
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigSources
 */
export interface ConfigSources {
    /**
     * 
     * @type {string}
     * @memberof ConfigSources
     */
    defaultsFile?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigSources
     */
    localFile?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigSources
     */
    envOverrides?: Array<string>;
}

/**
 * Check if a given object implements the ConfigSources interface.
 */
export function instanceOfConfigSources(value: object): value is ConfigSources {
    return true;
}

export function ConfigSourcesFromJSON(json: any): ConfigSources {
    return ConfigSourcesFromJSONTyped(json, false);
}

export function ConfigSourcesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigSources {
    if (json == null) {
        return json;
    }
    return {
        
        'defaultsFile': json['defaults_file'] == null ? undefined : json['defaults_file'],
        'localFile': json['local_file'] == null ? undefined : json['local_file'],
        'envOverrides': json['env_overrides'] == null ? undefined : json['env_overrides'],
    };
}

export function ConfigSourcesToJSON(json: any): ConfigSources {
    return ConfigSourcesToJSONTyped(json, false);
}

export function ConfigSourcesToJSONTyped(value?: ConfigSources | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'defaults_file': value['defaultsFile'],
        'local_file': value['localFile'],
        'env_overrides': value['envOverrides'],
    };
}

