/* tslint:disable */
/* eslint-disable */
/**
 * Orbit Container Agent API
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigSecurity
 */
export interface ConfigSecurity {
    /**
     * 
     * @type {boolean}
     * @memberof ConfigSecurity
     */
    authEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigSecurity
     */
    adminTokenPresent?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ConfigSecurity
     */
    staticTokens?: number;
}

/**
 * Check if a given object implements the ConfigSecurity interface.
 */
export function instanceOfConfigSecurity(value: object): value is ConfigSecurity {
    return true;
}

export function ConfigSecurityFromJSON(json: any): ConfigSecurity {
    return ConfigSecurityFromJSONTyped(json, false);
}

export function ConfigSecurityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigSecurity {
    if (json == null) {
        return json;
    }
    return {
        
        'authEnabled': json['auth_enabled'] == null ? undefined : json['auth_enabled'],
        'adminTokenPresent': json['admin_token_present'] == null ? undefined : json['admin_token_present'],
        'staticTokens': json['static_tokens'] == null ? undefined : json['static_tokens'],
    };
}

export function ConfigSecurityToJSON(json: any): ConfigSecurity {
    return ConfigSecurityToJSONTyped(json, false);
}

export function ConfigSecurityToJSONTyped(value?: ConfigSecurity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'auth_enabled': value['authEnabled'],
        'admin_token_present': value['adminTokenPresent'],
        'static_tokens': value['staticTokens'],
    };
}

