/* tslint:disable */
/* eslint-disable */
/**
 * Orbit Container Agent API
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigSecurity } from './ConfigSecurity';
import {
    ConfigSecurityFromJSON,
    ConfigSecurityFromJSONTyped,
    ConfigSecurityToJSON,
    ConfigSecurityToJSONTyped,
} from './ConfigSecurity';

/**
 * 
 * @export
 * @interface ConfigSnapshot
 */
export interface ConfigSnapshot {
    /**
     * 
     * @type {string}
     * @memberof ConfigSnapshot
     */
    containersRoot?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigSnapshot
     */
    telemetryLevel?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigSnapshot
     */
    apiBind?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigSnapshot
     */
    databasePath?: string;
    /**
     * 
     * @type {ConfigSecurity}
     * @memberof ConfigSnapshot
     */
    security?: ConfigSecurity;
}

/**
 * Check if a given object implements the ConfigSnapshot interface.
 */
export function instanceOfConfigSnapshot(value: object): value is ConfigSnapshot {
    return true;
}

export function ConfigSnapshotFromJSON(json: any): ConfigSnapshot {
    return ConfigSnapshotFromJSONTyped(json, false);
}

export function ConfigSnapshotFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigSnapshot {
    if (json == null) {
        return json;
    }
    return {
        
        'containersRoot': json['containers_root'] == null ? undefined : json['containers_root'],
        'telemetryLevel': json['telemetry_level'] == null ? undefined : json['telemetry_level'],
        'apiBind': json['api_bind'] == null ? undefined : json['api_bind'],
        'databasePath': json['database_path'] == null ? undefined : json['database_path'],
        'security': json['security'] == null ? undefined : ConfigSecurityFromJSON(json['security']),
    };
}

export function ConfigSnapshotToJSON(json: any): ConfigSnapshot {
    return ConfigSnapshotToJSONTyped(json, false);
}

export function ConfigSnapshotToJSONTyped(value?: ConfigSnapshot | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'containers_root': value['containersRoot'],
        'telemetry_level': value['telemetryLevel'],
        'api_bind': value['apiBind'],
        'database_path': value['databasePath'],
        'security': ConfigSecurityToJSON(value['security']),
    };
}

