/* tslint:disable */
/* eslint-disable */
/**
 * Orbit Container Agent API
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SecurityStatus } from './SecurityStatus';
import {
    SecurityStatusFromJSON,
    SecurityStatusFromJSONTyped,
    SecurityStatusToJSON,
    SecurityStatusToJSONTyped,
} from './SecurityStatus';
import type { ConfigSnapshot } from './ConfigSnapshot';
import {
    ConfigSnapshotFromJSON,
    ConfigSnapshotFromJSONTyped,
    ConfigSnapshotToJSON,
    ConfigSnapshotToJSONTyped,
} from './ConfigSnapshot';
import type { ConfigSources } from './ConfigSources';
import {
    ConfigSourcesFromJSON,
    ConfigSourcesFromJSONTyped,
    ConfigSourcesToJSON,
    ConfigSourcesToJSONTyped,
} from './ConfigSources';

/**
 * 
 * @export
 * @interface ConfigResponse
 */
export interface ConfigResponse {
    /**
     * 
     * @type {ConfigSnapshot}
     * @memberof ConfigResponse
     */
    config?: ConfigSnapshot;
    /**
     * 
     * @type {SecurityStatus}
     * @memberof ConfigResponse
     */
    security?: SecurityStatus;
    /**
     * 
     * @type {ConfigSources}
     * @memberof ConfigResponse
     */
    sources?: ConfigSources;
}

/**
 * Check if a given object implements the ConfigResponse interface.
 */
export function instanceOfConfigResponse(value: object): value is ConfigResponse {
    return true;
}

export function ConfigResponseFromJSON(json: any): ConfigResponse {
    return ConfigResponseFromJSONTyped(json, false);
}

export function ConfigResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : ConfigSnapshotFromJSON(json['config']),
        'security': json['security'] == null ? undefined : SecurityStatusFromJSON(json['security']),
        'sources': json['sources'] == null ? undefined : ConfigSourcesFromJSON(json['sources']),
    };
}

export function ConfigResponseToJSON(json: any): ConfigResponse {
    return ConfigResponseToJSONTyped(json, false);
}

export function ConfigResponseToJSONTyped(value?: ConfigResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': ConfigSnapshotToJSON(value['config']),
        'security': SecurityStatusToJSON(value['security']),
        'sources': ConfigSourcesToJSON(value['sources']),
    };
}

