/* tslint:disable */
/* eslint-disable */
/**
 * Orbit Container Agent API
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Container
 */
export interface Container {
    /**
     * 
     * @type {string}
     * @memberof Container
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Container
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Container
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Container
     */
    status: ContainerStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Container
     */
    platform: ContainerPlatformEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof Container
     */
    tags?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof Container
     */
    sizeBytes?: number;
    /**
     * 
     * @type {object}
     * @memberof Container
     */
    settings?: object;
    /**
     * 
     * @type {Date}
     * @memberof Container
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Container
     */
    updatedAt?: Date;
}


/**
 * @export
 */
export const ContainerStatusEnum = {
    Creating: 'creating',
    Ready: 'ready',
    Running: 'running',
    Error: 'error',
    Archived: 'archived'
} as const;
export type ContainerStatusEnum = typeof ContainerStatusEnum[keyof typeof ContainerStatusEnum];

/**
 * @export
 */
export const ContainerPlatformEnum = {
    WindowsX64: 'windows-x64',
    WindowsArm64: 'windows-arm64'
} as const;
export type ContainerPlatformEnum = typeof ContainerPlatformEnum[keyof typeof ContainerPlatformEnum];


/**
 * Check if a given object implements the Container interface.
 */
export function instanceOfContainer(value: object): value is Container {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ContainerFromJSON(json: any): Container {
    return ContainerFromJSONTyped(json, false);
}

export function ContainerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Container {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'status': json['status'],
        'platform': json['platform'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'sizeBytes': json['size_bytes'] == null ? undefined : json['size_bytes'],
        'settings': json['settings'] == null ? undefined : json['settings'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function ContainerToJSON(json: any): Container {
    return ContainerToJSONTyped(json, false);
}

export function ContainerToJSONTyped(value?: Container | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'status': value['status'],
        'platform': value['platform'],
        'tags': value['tags'],
        'size_bytes': value['sizeBytes'],
        'settings': value['settings'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

