/* tslint:disable */
/* eslint-disable */
/**
 * Orbit Container Agent API
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContainersContainerIdAppsPostRequest
 */
export interface ContainersContainerIdAppsPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ContainersContainerIdAppsPostRequest
     */
    installerPath?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainersContainerIdAppsPostRequest
     */
    silentArgs?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainersContainerIdAppsPostRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the ContainersContainerIdAppsPostRequest interface.
 */
export function instanceOfContainersContainerIdAppsPostRequest(value: object): value is ContainersContainerIdAppsPostRequest {
    return true;
}

export function ContainersContainerIdAppsPostRequestFromJSON(json: any): ContainersContainerIdAppsPostRequest {
    return ContainersContainerIdAppsPostRequestFromJSONTyped(json, false);
}

export function ContainersContainerIdAppsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainersContainerIdAppsPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'installerPath': json['installer_path'] == null ? undefined : json['installer_path'],
        'silentArgs': json['silent_args'] == null ? undefined : json['silent_args'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ContainersContainerIdAppsPostRequestToJSON(json: any): ContainersContainerIdAppsPostRequest {
    return ContainersContainerIdAppsPostRequestToJSONTyped(json, false);
}

export function ContainersContainerIdAppsPostRequestToJSONTyped(value?: ContainersContainerIdAppsPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'installer_path': value['installerPath'],
        'silent_args': value['silentArgs'],
        'name': value['name'],
    };
}

