/* tslint:disable */
/* eslint-disable */
/**
 * Orbit Container Agent API
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContainersContainerIdSnapshotsPostRequest
 */
export interface ContainersContainerIdSnapshotsPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ContainersContainerIdSnapshotsPostRequest
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainersContainerIdSnapshotsPostRequest
     */
    type?: ContainersContainerIdSnapshotsPostRequestTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ContainersContainerIdSnapshotsPostRequest
     */
    baseSnapshotId?: string;
}


/**
 * @export
 */
export const ContainersContainerIdSnapshotsPostRequestTypeEnum = {
    Full: 'full',
    Delta: 'delta'
} as const;
export type ContainersContainerIdSnapshotsPostRequestTypeEnum = typeof ContainersContainerIdSnapshotsPostRequestTypeEnum[keyof typeof ContainersContainerIdSnapshotsPostRequestTypeEnum];


/**
 * Check if a given object implements the ContainersContainerIdSnapshotsPostRequest interface.
 */
export function instanceOfContainersContainerIdSnapshotsPostRequest(value: object): value is ContainersContainerIdSnapshotsPostRequest {
    return true;
}

export function ContainersContainerIdSnapshotsPostRequestFromJSON(json: any): ContainersContainerIdSnapshotsPostRequest {
    return ContainersContainerIdSnapshotsPostRequestFromJSONTyped(json, false);
}

export function ContainersContainerIdSnapshotsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainersContainerIdSnapshotsPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'] == null ? undefined : json['label'],
        'type': json['type'] == null ? undefined : json['type'],
        'baseSnapshotId': json['base_snapshot_id'] == null ? undefined : json['base_snapshot_id'],
    };
}

export function ContainersContainerIdSnapshotsPostRequestToJSON(json: any): ContainersContainerIdSnapshotsPostRequest {
    return ContainersContainerIdSnapshotsPostRequestToJSONTyped(json, false);
}

export function ContainersContainerIdSnapshotsPostRequestToJSONTyped(value?: ContainersContainerIdSnapshotsPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'type': value['type'],
        'base_snapshot_id': value['baseSnapshotId'],
    };
}

