/* tslint:disable */
/* eslint-disable */
/**
 * Orbit Container Agent API
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContainersPostRequest
 */
export interface ContainersPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ContainersPostRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ContainersPostRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainersPostRequest
     */
    platform: string;
    /**
     * 
     * @type {object}
     * @memberof ContainersPostRequest
     */
    settings?: object;
}

/**
 * Check if a given object implements the ContainersPostRequest interface.
 */
export function instanceOfContainersPostRequest(value: object): value is ContainersPostRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    return true;
}

export function ContainersPostRequestFromJSON(json: any): ContainersPostRequest {
    return ContainersPostRequestFromJSONTyped(json, false);
}

export function ContainersPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainersPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'platform': json['platform'],
        'settings': json['settings'] == null ? undefined : json['settings'],
    };
}

export function ContainersPostRequestToJSON(json: any): ContainersPostRequest {
    return ContainersPostRequestToJSONTyped(json, false);
}

export function ContainersPostRequestToJSONTyped(value?: ContainersPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'platform': value['platform'],
        'settings': value['settings'],
    };
}

