/* tslint:disable */
/* eslint-disable */
/**
 * Orbit Container Agent API
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SecurityTokensPostRequest
 */
export interface SecurityTokensPostRequest {
    /**
     * Etiqueta descriptiva del token
     * @type {string}
     * @memberof SecurityTokensPostRequest
     */
    name: string;
}

/**
 * Check if a given object implements the SecurityTokensPostRequest interface.
 */
export function instanceOfSecurityTokensPostRequest(value: object): value is SecurityTokensPostRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function SecurityTokensPostRequestFromJSON(json: any): SecurityTokensPostRequest {
    return SecurityTokensPostRequestFromJSONTyped(json, false);
}

export function SecurityTokensPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecurityTokensPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function SecurityTokensPostRequestToJSON(json: any): SecurityTokensPostRequest {
    return SecurityTokensPostRequestToJSONTyped(json, false);
}

export function SecurityTokensPostRequestToJSONTyped(value?: SecurityTokensPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

