/* tslint:disable */
/* eslint-disable */
/**
 * Orbit Container Agent API
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SecurityStatus
 */
export interface SecurityStatus {
    /**
     * 
     * @type {boolean}
     * @memberof SecurityStatus
     */
    authEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SecurityStatus
     */
    adminTokenPresent: boolean;
    /**
     * 
     * @type {number}
     * @memberof SecurityStatus
     */
    staticTokenCount: number;
    /**
     * 
     * @type {number}
     * @memberof SecurityStatus
     */
    managedTokenCount: number;
    /**
     * 
     * @type {number}
     * @memberof SecurityStatus
     */
    expiringTokenCount: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof SecurityStatus
     */
    scopesCatalog: Array<string>;
}

/**
 * Check if a given object implements the SecurityStatus interface.
 */
export function instanceOfSecurityStatus(value: object): value is SecurityStatus {
    if (!('authEnabled' in value) || value['authEnabled'] === undefined) return false;
    if (!('adminTokenPresent' in value) || value['adminTokenPresent'] === undefined) return false;
    if (!('staticTokenCount' in value) || value['staticTokenCount'] === undefined) return false;
    if (!('managedTokenCount' in value) || value['managedTokenCount'] === undefined) return false;
    if (!('expiringTokenCount' in value) || value['expiringTokenCount'] === undefined) return false;
    if (!('scopesCatalog' in value) || value['scopesCatalog'] === undefined) return false;
    return true;
}

export function SecurityStatusFromJSON(json: any): SecurityStatus {
    return SecurityStatusFromJSONTyped(json, false);
}

export function SecurityStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecurityStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'authEnabled': json['auth_enabled'],
        'adminTokenPresent': json['admin_token_present'],
        'staticTokenCount': json['static_token_count'],
        'managedTokenCount': json['managed_token_count'],
        'expiringTokenCount': json['expiring_token_count'],
        'scopesCatalog': json['scopes_catalog'],
    };
}

export function SecurityStatusToJSON(json: any): SecurityStatus {
    return SecurityStatusToJSONTyped(json, false);
}

export function SecurityStatusToJSONTyped(value?: SecurityStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'auth_enabled': value['authEnabled'],
        'admin_token_present': value['adminTokenPresent'],
        'static_token_count': value['staticTokenCount'],
        'managed_token_count': value['managedTokenCount'],
        'expiring_token_count': value['expiringTokenCount'],
        'scopes_catalog': value['scopesCatalog'],
    };
}

