/* tslint:disable */
/* eslint-disable */
/**
 * Orbit Container Agent API
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Snapshot
 */
export interface Snapshot {
    /**
     * 
     * @type {string}
     * @memberof Snapshot
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Snapshot
     */
    containerId?: string;
    /**
     * 
     * @type {string}
     * @memberof Snapshot
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof Snapshot
     */
    type?: SnapshotTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Snapshot
     */
    baseSnapshotId?: string;
    /**
     * 
     * @type {number}
     * @memberof Snapshot
     */
    sizeBytes?: number;
    /**
     * 
     * @type {Date}
     * @memberof Snapshot
     */
    createdAt?: Date;
}


/**
 * @export
 */
export const SnapshotTypeEnum = {
    Full: 'full',
    Delta: 'delta'
} as const;
export type SnapshotTypeEnum = typeof SnapshotTypeEnum[keyof typeof SnapshotTypeEnum];


/**
 * Check if a given object implements the Snapshot interface.
 */
export function instanceOfSnapshot(value: object): value is Snapshot {
    return true;
}

export function SnapshotFromJSON(json: any): Snapshot {
    return SnapshotFromJSONTyped(json, false);
}

export function SnapshotFromJSONTyped(json: any, ignoreDiscriminator: boolean): Snapshot {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'containerId': json['container_id'] == null ? undefined : json['container_id'],
        'label': json['label'] == null ? undefined : json['label'],
        'type': json['type'] == null ? undefined : json['type'],
        'baseSnapshotId': json['base_snapshot_id'] == null ? undefined : json['base_snapshot_id'],
        'sizeBytes': json['size_bytes'] == null ? undefined : json['size_bytes'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function SnapshotToJSON(json: any): Snapshot {
    return SnapshotToJSONTyped(json, false);
}

export function SnapshotToJSONTyped(value?: Snapshot | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'container_id': value['containerId'],
        'label': value['label'],
        'type': value['type'],
        'base_snapshot_id': value['baseSnapshotId'],
        'size_bytes': value['sizeBytes'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

