/* tslint:disable */
/* eslint-disable */
/**
 * Orbit Container Agent API
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemInfoGet200Response
 */
export interface SystemInfoGet200Response {
    /**
     * 
     * @type {string}
     * @memberof SystemInfoGet200Response
     */
    version?: string;
    /**
     * 
     * @type {string}
     * @memberof SystemInfoGet200Response
     */
    build?: string;
    /**
     * 
     * @type {number}
     * @memberof SystemInfoGet200Response
     */
    uptimeSeconds?: number;
    /**
     * 
     * @type {string}
     * @memberof SystemInfoGet200Response
     */
    driverStatus?: string;
}

/**
 * Check if a given object implements the SystemInfoGet200Response interface.
 */
export function instanceOfSystemInfoGet200Response(value: object): value is SystemInfoGet200Response {
    return true;
}

export function SystemInfoGet200ResponseFromJSON(json: any): SystemInfoGet200Response {
    return SystemInfoGet200ResponseFromJSONTyped(json, false);
}

export function SystemInfoGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemInfoGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'] == null ? undefined : json['version'],
        'build': json['build'] == null ? undefined : json['build'],
        'uptimeSeconds': json['uptime_seconds'] == null ? undefined : json['uptime_seconds'],
        'driverStatus': json['driver_status'] == null ? undefined : json['driver_status'],
    };
}

export function SystemInfoGet200ResponseToJSON(json: any): SystemInfoGet200Response {
    return SystemInfoGet200ResponseToJSONTyped(json, false);
}

export function SystemInfoGet200ResponseToJSONTyped(value?: SystemInfoGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'build': value['build'],
        'uptime_seconds': value['uptimeSeconds'],
        'driver_status': value['driverStatus'],
    };
}

