/*
 * Orbit Container Agent API
 *
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`apps_app_id_launch_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AppsAppIdLaunchPostError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`containers_container_id_apps_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ContainersContainerIdAppsGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`containers_container_id_apps_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ContainersContainerIdAppsPostError {
    UnknownValue(serde_json::Value),
}

pub async fn apps_app_id_launch_post(
    configuration: &configuration::Configuration,
    app_id: &str,
    apps_app_id_launch_post_request: Option<models::AppsAppIdLaunchPostRequest>,
) -> Result<models::Task, Error<AppsAppIdLaunchPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_app_id = app_id;
    let p_body_apps_app_id_launch_post_request = apps_app_id_launch_post_request;

    let uri_str = format!(
        "{}/apps/{appId}/launch",
        configuration.base_path,
        appId = crate::apis::urlencode(p_path_app_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_apps_app_id_launch_post_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Task`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Task`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AppsAppIdLaunchPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn containers_container_id_apps_get(
    configuration: &configuration::Configuration,
    container_id: &str,
) -> Result<Vec<models::AppInstance>, Error<ContainersContainerIdAppsGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_container_id = container_id;

    let uri_str = format!(
        "{}/containers/{containerId}/apps",
        configuration.base_path,
        containerId = crate::apis::urlencode(p_path_container_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::AppInstance&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::AppInstance&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ContainersContainerIdAppsGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn containers_container_id_apps_post(
    configuration: &configuration::Configuration,
    container_id: &str,
    containers_container_id_apps_post_request: models::ContainersContainerIdAppsPostRequest,
) -> Result<models::Task, Error<ContainersContainerIdAppsPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_container_id = container_id;
    let p_body_containers_container_id_apps_post_request =
        containers_container_id_apps_post_request;

    let uri_str = format!(
        "{}/containers/{containerId}/apps",
        configuration.base_path,
        containerId = crate::apis::urlencode(p_path_container_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_containers_container_id_apps_post_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Task`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Task`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ContainersContainerIdAppsPostError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
