/*
 * Orbit Container Agent API
 *
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppsAppIdLaunchPostRequest {
    #[serde(rename = "entry_point_id", skip_serializing_if = "Option::is_none")]
    pub entry_point_id: Option<String>,
    #[serde(rename = "args", skip_serializing_if = "Option::is_none")]
    pub args: Option<Vec<String>>,
}

impl AppsAppIdLaunchPostRequest {
    pub fn new() -> AppsAppIdLaunchPostRequest {
        AppsAppIdLaunchPostRequest {
            entry_point_id: None,
            args: None,
        }
    }
}

