/*
 * Orbit Container Agent API
 *
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainersContainerIdSnapshotsPostRequest {
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    #[serde(rename = "base_snapshot_id", skip_serializing_if = "Option::is_none")]
    pub base_snapshot_id: Option<uuid::Uuid>,
}

impl ContainersContainerIdSnapshotsPostRequest {
    pub fn new() -> ContainersContainerIdSnapshotsPostRequest {
        ContainersContainerIdSnapshotsPostRequest {
            label: None,
            r#type: None,
            base_snapshot_id: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "full")]
    Full,
    #[serde(rename = "delta")]
    Delta,
}

impl Default for Type {
    fn default() -> Type {
        Self::Full
    }
}

