/*
 * Orbit Container Agent API
 *
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainersContainerIdAppsPostRequest {
    #[serde(rename = "installer_path", skip_serializing_if = "Option::is_none")]
    pub installer_path: Option<String>,
    #[serde(rename = "silent_args", skip_serializing_if = "Option::is_none")]
    pub silent_args: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl ContainersContainerIdAppsPostRequest {
    pub fn new() -> ContainersContainerIdAppsPostRequest {
        ContainersContainerIdAppsPostRequest {
            installer_path: None,
            silent_args: None,
            name: None,
        }
    }
}
