/*
 * Orbit Container Agent API
 *
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecurityTokensPostRequest {
    /// Etiqueta descriptiva del token
    #[serde(rename = "name")]
    pub name: String,
}

impl SecurityTokensPostRequest {
    pub fn new(name: String) -> SecurityTokensPostRequest {
        SecurityTokensPostRequest {
            name,
        }
    }
}

