/*
 * Orbit Container Agent API
 *
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemInfoGet200Response {
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "build", skip_serializing_if = "Option::is_none")]
    pub build: Option<String>,
    #[serde(rename = "uptime_seconds", skip_serializing_if = "Option::is_none")]
    pub uptime_seconds: Option<i32>,
    #[serde(rename = "driver_status", skip_serializing_if = "Option::is_none")]
    pub driver_status: Option<String>,
}

impl SystemInfoGet200Response {
    pub fn new() -> SystemInfoGet200Response {
        SystemInfoGet200Response {
            version: None,
            build: None,
            uptime_seconds: None,
            driver_status: None,
        }
    }
}
