/*
 * Orbit Container Agent API
 *
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiToken {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "prefix")]
    pub prefix: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "revoked_at", skip_serializing_if = "Option::is_none")]
    pub revoked_at: Option<String>,
}

impl ApiToken {
    pub fn new(id: uuid::Uuid, name: String, prefix: String, created_at: String) -> ApiToken {
        ApiToken {
            id,
            name,
            prefix,
            created_at,
            revoked_at: None,
        }
    }
}

