/*
 * Orbit Container Agent API
 *
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiTokenCreated {
    /// Token completo devuelto solo una vez
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "info")]
    pub info: Box<models::ApiToken>,
}

impl ApiTokenCreated {
    pub fn new(token: String, info: models::ApiToken) -> ApiTokenCreated {
        ApiTokenCreated {
            token,
            info: Box::new(info),
        }
    }
}

