/*
 * Orbit Container Agent API
 *
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppInstance {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "container_id")]
    pub container_id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "entry_points", skip_serializing_if = "Option::is_none")]
    pub entry_points: Option<Vec<models::AppInstanceEntryPointsInner>>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
}

impl AppInstance {
    pub fn new(id: uuid::Uuid, container_id: uuid::Uuid, name: String, status: Status) -> AppInstance {
        AppInstance {
            id,
            container_id,
            name,
            version: None,
            status,
            entry_points: None,
            created_at: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "installing")]
    Installing,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for Status {
    fn default() -> Status {
        Self::Installing
    }
}

