/*
 * Orbit Container Agent API
 *
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigSources {
    #[serde(rename = "defaults_file", skip_serializing_if = "Option::is_none")]
    pub defaults_file: Option<String>,
    #[serde(rename = "local_file", skip_serializing_if = "Option::is_none")]
    pub local_file: Option<String>,
    #[serde(rename = "env_overrides", skip_serializing_if = "Option::is_none")]
    pub env_overrides: Option<Vec<String>>,
}

impl ConfigSources {
    pub fn new() -> ConfigSources {
        ConfigSources {
            defaults_file: None,
            local_file: None,
            env_overrides: None,
        }
    }
}

