/*
 * Orbit Container Agent API
 *
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigSecurity {
    #[serde(rename = "auth_enabled", skip_serializing_if = "Option::is_none")]
    pub auth_enabled: Option<bool>,
    #[serde(rename = "admin_token_present", skip_serializing_if = "Option::is_none")]
    pub admin_token_present: Option<bool>,
    #[serde(rename = "static_tokens", skip_serializing_if = "Option::is_none")]
    pub static_tokens: Option<i32>,
}

impl ConfigSecurity {
    pub fn new() -> ConfigSecurity {
        ConfigSecurity {
            auth_enabled: None,
            admin_token_present: None,
            static_tokens: None,
        }
    }
}

