/*
 * Orbit Container Agent API
 *
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigSnapshot {
    #[serde(rename = "containers_root", skip_serializing_if = "Option::is_none")]
    pub containers_root: Option<String>,
    #[serde(rename = "telemetry_level", skip_serializing_if = "Option::is_none")]
    pub telemetry_level: Option<String>,
    #[serde(rename = "api_bind", skip_serializing_if = "Option::is_none")]
    pub api_bind: Option<String>,
    #[serde(rename = "database_path", skip_serializing_if = "Option::is_none")]
    pub database_path: Option<String>,
    #[serde(rename = "security", skip_serializing_if = "Option::is_none")]
    pub security: Option<Box<models::ConfigSecurity>>,
}

impl ConfigSnapshot {
    pub fn new() -> ConfigSnapshot {
        ConfigSnapshot {
            containers_root: None,
            telemetry_level: None,
            api_bind: None,
            database_path: None,
            security: None,
        }
    }
}

