/*
 * Orbit Container Agent API
 *
 * API REST del agente Orbit para gestionar contenedores portables, instalaciones de aplicaciones y tareas asíncronas. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecurityStatus {
    #[serde(rename = "auth_enabled")]
    pub auth_enabled: bool,
    #[serde(rename = "admin_token_present")]
    pub admin_token_present: bool,
    #[serde(rename = "static_token_count")]
    pub static_token_count: i32,
    #[serde(rename = "managed_token_count")]
    pub managed_token_count: i32,
    #[serde(rename = "expiring_token_count")]
    pub expiring_token_count: i32,
    #[serde(rename = "scopes_catalog")]
    pub scopes_catalog: Vec<String>,
}

impl SecurityStatus {
    pub fn new(auth_enabled: bool, admin_token_present: bool, static_token_count: i32, managed_token_count: i32, expiring_token_count: i32, scopes_catalog: Vec<String>) -> SecurityStatus {
        SecurityStatus {
            auth_enabled,
            admin_token_present,
            static_token_count,
            managed_token_count,
            expiring_token_count,
            scopes_catalog,
        }
    }
}

